### ISSUE TITLE
Need this checked 

### ISSUE THREAD

**Issue by narendasan** [CS196Illinois/theDoctor#4]
Disc. of the problem or the commit: 
457a2afcce1fe1883f0d7058bcd620a81d9a91b5

**Comment by akuznets0v** [comment]
A mediocre introduction, followed by an intense dramatization of events not yet a full year old. A unsatisfactory cliffhanger ending, scarcely justified by the impact of the dearth of resolution.

6/10.

**Comment by tanishq-dubey** [comment]
I felt as if it were more a betrayal of a supporting lead by the lead, Followed by the supporting lead's strong, yet suave rebuttal that exposed the insecurities of the lead character's understanding of the world around him, ending with the supporting lead bringing a prompt resolution to everything that had led up to this point in a swift action.

**Comment by shotaroikeda** [comment]
Did someone say [Swift](https://github.com/apple/swift)?

**Comment by narendasan** [comment]
100% most convoluted application dev process ever, need to dev in feature branch, merge to dev, merge to staging to build, then commit the changes in the complied site into a sub-tree gh-pages to test, then merge gh-pages to production, zip that up with a fancy code name, add it as a release, tell @modi95 to load it to engrit which apparently takes 30 min, and then hope firebase doesn't figure out 200 people are trying to access this site at once.

**Comment by narendasan** [comment]
Would say the #1 thriller at the box office this summer

**Comment by tanishq-dubey** [comment]
> hope firebase doesn't figure out 200 people are trying to access this site at once

More like hope we bought a premium account to support more than 50 accounts

**Comment by narendasan** [comment]
sssh *spoiler alert*

**Comment by modi95** [comment]
LOL Yeah we're going to have that fixed for the upcoming semester. @pranaygp

**Comment by modi95** [comment]
Also @tanishq-dubey , yes we have a premium account. We're paying $50 a month for it.
